version: '3'

services:
  flask_app:
<<<<<<< HEAD
    build: .
=======
    build:
      context: ./flask_app
      dockerfile: Dockerfile
>>>>>>> f923958493f9c3a30ec5a8d3f6ff892b4a0500b9
    ports:
      - 5000:5000
    volumes:
      - ./flask_app:/app/flask_app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:Favour98@localhost/halo

  db:
    image: postgres
    environment:
      - POSTGRES_DB=halo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Favour98
    volumes:
      - ./data:/var/lib/postgresql/data
