version: '3.9'

services:
  database:
    restart: always
    image: postgres:13-alpine
    container_name: haloo_db
    environment:
      - POSTGRES_PASSWORD=Favour98
      - POSTGRES_USER=postgres
      - POSTGRES_DB=halo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    restart: always
    container_name: halo_web
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DOCKER_ENV=true
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=halo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Favour98

volumes:
  postgres_data:
