name: CI 

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Set up Node.js 
      uses: actions/setup-node@v3 
      with:
        node-version: '14'

    - name: Install Node.js dependencies 
      run: |
        cd reactFrontend
        npm install

    - name: Build React app
      run: |
        cd reactFrontenddd
        npm run build 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Flask tests  
      run: |
        cd Test
        python -m unittest discover 
    
    - name: Run JavaScript tests
      run: |
        cd reactFrontenddd/src/__test__
        npm test
